# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
# Giang Duong <giang@dtt.vn>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-04 06:08+0000\n"
"PO-Revision-Date: 2014-07-16 14:42+0000\n"
"Last-Translator: Giang Duong <giang@dtt.vn>\n"
"Language-Team: Vietnamese (Viet Nam) (http://www.transifex.com/projects/p/"
"ceilometer/language/vi_VN/)\n"
"Language: vi_VN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ceilometer/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Ngoại lệ ban đầu được giảm xuống: %s"

#: ceilometer/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Ngoại lệ bất ngờ xảy ra %d thời gian(s) ... thử lại"

#: ceilometer/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Không thể nhả ra khóa đã bị chiếm dụng `%s`"

#: ceilometer/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "trong cuộc gọi vòng lặp thời khoảng cố định "

#: ceilometer/openstack/common/loopingcall.py:131
msgid "in dynamic looping call"
msgstr "trong cuộc gọi lặp động"

#: ceilometer/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "Không hiểu luật %s"

#: ceilometer/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Không có bộ xử lý thích ứng của loại %s"

#: ceilometer/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "Không hiểu luật %r"

#: ceilometer/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Ngoại lệ trong quá trình dọn dẹp RPC"

#: ceilometer/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "ngoại lệ không được quản lý"

#: ceilometer/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr "DB vượt quá giới hạn thử lại."

#: ceilometer/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "DB lỗi kết nối."

#: ceilometer/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "Lỗi exception DB khi bao bọc."

#: ceilometer/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr "Không thể di chuyển lên phiên bản %s trên công cụ %s"

#: ceilometer/openstack/common/middleware/catch_errors.py:40
#, python-format
msgid "An error occurred during processing the request: %s"
msgstr "Một lỗi xảy ra trong quá trình xử lý yêu cầu: %s"
